main: io.github.Leonardo0013YT.UltraMinions.Main
author: Bhavesh
version: 6.0.0
api-version: "1.21"
name: UltraMinions
load: POSTWORLD
softdepend:
  - Vault
  - LuckPerms
  - Essentials
  - ShopGUIPlus
  - PlaceholderAPI
commands:
  msetup:
  minions:
    description: UltraMinions commands including save, load, list, setup and administration.
    usage: /minions <save|load|list|setup|give|reload|shop|forcesave|food|autosell|autosmelt|compressor|fuel|setmaxminion>
